apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: apps
  labels:
    prometheus: prometheus-standalone
    k8s-app: apps
spec:
  jobLabel: rabbitmq
  selector:
    matchLabels:
      app: rabbitmq
  namespaceSelector:
    matchNames:
    - default
  endpoints:
  - port: prometheus
    interval: 5s