apiVersion: v1
kind: PersistentVolume 
metadata:
  name: postgres-pv-volume 
  labels:
    type: local
    app: postgres
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes: 
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
spec:
  storageClassName: standard
  accessModes: 
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
