apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deploy
spec:
  selector:
    matchLabels:
      app: prometheus
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus
          imagePullPolicy: "IfNotPresent"
          ports:
          - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-svc
  labels:
    app: prometheus
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090